<?php

namespace Tests\Unit\Branch;

use App\Model\Todo;
use App\Repositories\TodosRepository;
use Tests\TestCase;

class TodoTest extends TestCase
{
    protected $repository;
    protected function setUp(): void
    {
       $this->repository = new TodosRepository( new Todo());
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * To add to do list.
     * @group testAddTodo
     * @return void
     */
    public function testAddTodo()
    {

        $data =[
            ['title'=>'one'],
            ['title' => 'two'],
            ];
        $response = $this->repository->createOrUpdateIfNotExitDelete($data);
        
        $this->assertTrue(true);
    }

    /**
     * get all to do list.
     * @group testGetAllTodo
     * @return void
     */
    public function testGetAllTodo()
    {

        $response = $this->repository->all();
        $this->assertNotEmpty($response);
    }
    
}
